### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by vladozar**

### CODE REVIEW

**Comment by grunt2001c** [comment]
put the translation master file in transfex, then you will be able to get lots more translations, and it's easier to manager

**Comment by vladozar** [comment]
Transfex is a good idea, but here are the issues with it.

- It's a paid product. The donation for SoftProjector won't come even close to cover the cost of the least expensive package. 
- Qt has its own translation manager called QtLinquist, which is pretty good in managing translation and can it integrates with the code. http://doc.qt.io/qt-5/qtlinguist-index.html

**Comment by grunt2001c** [comment]
hmm, they've used to be free for open source projects. I've used them for my project zefaniabible.com before and they were great. 
see below from their site.

We are proud and humbled to be hosting the largest Open Source translation community in the world. We offer Transifex for free to Open Source projects that have no funding, revenue, and/or commercialization model. If you have a question whether your organization qualifies for our Open Source program, please contact us.

**Comment by vladozar** [comment]
ok, I see, this note is in the FQA, and not straight forward. I will give it a try.

**Comment by grunt2001c** [comment]
there is a joomla plugin also that allows you to automatically pull the translation from the their site and zip it up into zip file or straight download. something like here.
http://www.zefaniabible.com/download/language-packs.html

**Pull request merged**
